package com.example.greetandeat2

// Represents a single menu item
data class MenuItem(
    val id: String,
    val name: String,
    val price: Double
)

// Represents a restaurant with a menu
data class Restaurant(
    val id: String,
    val name: String,
    val menu: List<MenuItem>
)

// Represents a user order
data class Order(
    val id: String?,          // generated by the API
    val userId: String,       // Firebase UID
    val items: List<MenuItem>,
    val total: Double
)
